\<html>
	\<body>
		\<p>\<b>Ticket ID:\</b> <rentAbuseTicketId>\</p>
		\<p>\<b>Date abuz:\</b>\</p>
		\<p>Email raportor: <rentAbuseEmail>\</p>
		\<p>Telefon raportor: <rentAbusePhone>\</p>
		\<p>Detalii abuz:\<br/>
		\<i><rentAbuseDescription>\</i>\</p>
		\<p>\<b>Detalii chirie:\</b>\</p>
		\<img src="<rentAbuseRentImage>" alt="Prima poza" style="width:400px;height:300px">
		\<p><rentAbuseRentDetails>\</p>
		\<p>Telefon proprietar: <rentAbuseRentPhone>\</p>
		\<p>\<a href="<appUrl>/report-validation.html?rentAbuseTokenKey=<rentAbuseTokenKey>">Solutionare abuz\</a>\</p>
		\<br/>\<br/>
	\</body>
\</html>