\<html>
	\<body>
		\<p>Ticket ID: <rentAbuseTicketId>\</p>
		\<p>\<br/>Acesta este un răspuns automat.\</p>
		\<p>\<br/>Sesizarea dumneavoastră a fost inaintată departamentului de sesizări Fizbo și veți fi contactat \<br/>
		in cel mai scurt timp posibil. In continuare găsiți și textul sesizării:\</p>
		\<p>\<i><rentAbuseDescription>\</i>\</p>
		\<p>\<br/>Vă mulțumim pentru notificare,\</p>
		\<p>Echipa Fizbo\</p>
	\</body>
\</html> 